# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from workday_performance_enablement_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from workday_performance_enablement_python_sdk.api_response import AsyncGeneratorResponse
from workday_performance_enablement_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_performance_enablement_python_sdk import schemas  # noqa: F401

from workday_performance_enablement_python_sdk.model.about_worker_d396fd5bffec1000100f44a5808f0005 import AboutWorkerD396fd5bffec1000100f44a5808f0005 as AboutWorkerD396fd5bffec1000100f44a5808f0005Schema
from workday_performance_enablement_python_sdk.model.requested_by_d396fd5bffec1000100f44a5808f0006 import RequestedByD396fd5bffec1000100f44a5808f0006 as RequestedByD396fd5bffec1000100f44a5808f0006Schema
from workday_performance_enablement_python_sdk.model.give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 import GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000 as GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Schema
from workday_performance_enablement_python_sdk.model.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCESchema
from workday_performance_enablement_python_sdk.model.business_process_parameters_d396fd5bffec1000100f440bde4c0001 import BusinessProcessParametersD396fd5bffec1000100f440bde4c0001 as BusinessProcessParametersD396fd5bffec1000100f440bde4c0001Schema
from workday_performance_enablement_python_sdk.model.requested_feedback_comments_d396fd5bffec10001393477e77870000 import RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 as RequestedFeedbackCommentsD396fd5bffec10001393477e77870000Schema
from workday_performance_enablement_python_sdk.model.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCESchema

from workday_performance_enablement_python_sdk.type.give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 import GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000
from workday_performance_enablement_python_sdk.type.requested_feedback_comments_d396fd5bffec10001393477e77870000 import RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
from workday_performance_enablement_python_sdk.type.requested_by_d396fd5bffec1000100f44a5808f0006 import RequestedByD396fd5bffec1000100f44a5808f0006
from workday_performance_enablement_python_sdk.type.about_worker_d396fd5bffec1000100f44a5808f0005 import AboutWorkerD396fd5bffec1000100f44a5808f0005
from workday_performance_enablement_python_sdk.type.errormodelreference import ERRORMODELREFERENCE
from workday_performance_enablement_python_sdk.type.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE
from workday_performance_enablement_python_sdk.type.business_process_parameters_d396fd5bffec1000100f440bde4c0001 import BusinessProcessParametersD396fd5bffec1000100f440bde4c0001

from ...api_client import Dictionary
from workday_performance_enablement_python_sdk.pydantic.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCEPydantic
from workday_performance_enablement_python_sdk.pydantic.requested_feedback_comments_d396fd5bffec10001393477e77870000 import RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 as RequestedFeedbackCommentsD396fd5bffec10001393477e77870000Pydantic
from workday_performance_enablement_python_sdk.pydantic.about_worker_d396fd5bffec1000100f44a5808f0005 import AboutWorkerD396fd5bffec1000100f44a5808f0005 as AboutWorkerD396fd5bffec1000100f44a5808f0005Pydantic
from workday_performance_enablement_python_sdk.pydantic.business_process_parameters_d396fd5bffec1000100f440bde4c0001 import BusinessProcessParametersD396fd5bffec1000100f440bde4c0001 as BusinessProcessParametersD396fd5bffec1000100f440bde4c0001Pydantic
from workday_performance_enablement_python_sdk.pydantic.give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 import GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000 as GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic
from workday_performance_enablement_python_sdk.pydantic.requested_by_d396fd5bffec1000100f44a5808f0006 import RequestedByD396fd5bffec1000100f44a5808f0006 as RequestedByD396fd5bffec1000100f44a5808f0006Pydantic
from workday_performance_enablement_python_sdk.pydantic.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCEPydantic

from . import path

# Path params
IDSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'ID': typing.Union[IDSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_id = api_client.PathParameter(
    name="ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IDSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Schema


request_body_give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Schema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = ERRORMODELREFERENCESchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ERRORMODELREFERENCE


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ERRORMODELREFERENCE


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '401': _response_for_401,
    '403': _response_for_403,
    '404': _response_for_404,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_event_mapped_args(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if due_date is not None:
            _body["dueDate"] = due_date
        if feedback_given_date is not None:
            _body["feedbackGivenDate"] = feedback_given_date
        if feedback_creation_date is not None:
            _body["feedbackCreationDate"] = feedback_creation_date
        if requested_by is not None:
            _body["requestedBy"] = requested_by
        if about_worker is not None:
            _body["aboutWorker"] = about_worker
        if expiration_date is not None:
            _body["expirationDate"] = expiration_date
        if display_nameof_responder is not None:
            _body["displayNameofResponder"] = display_nameof_responder
        if feedback_comments is not None:
            _body["feedbackComments"] = feedback_comments
        if business_process_parameters is not None:
            _body["businessProcessParameters"] = business_process_parameters
        if feedback_private is not None:
            _body["feedbackPrivate"] = feedback_private
        if feedback_confidential is not None:
            _body["feedbackConfidential"] = feedback_confidential
        if id is not None:
            _body["id"] = id
        if descriptor is not None:
            _body["descriptor"] = descriptor
        args.body = _body
        if id is not None:
            _path_params["ID"] = id
        args.path = _path_params
        return args

    async def _aupdate_event_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Updates the Give Requested Feedback Event that matches the WID in the url, and the current authenticated user is a responder for the event.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/giveRequestedFeedbackEvents/{ID}',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_event_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Updates the Give Requested Feedback Event that matches the WID in the url, and the current authenticated user is a responder for the event.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/giveRequestedFeedbackEvents/{ID}',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdateEventRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_event(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_event_mapped_args(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
        )
        return await self._aupdate_event_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def update_event(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_event_mapped_args(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
        )
        return self._update_event_oapg(
            body=args.body,
            path_params=args.path,
        )

class UpdateEvent(BaseApi):

    async def aupdate_event(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic:
        raw_response = await self.raw.aupdate_event(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
            **kwargs,
        )
        if validate:
            return RootModel[GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic, raw_response.body)
    
    
    def update_event(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
    ) -> GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic:
        raw_response = self.raw.update_event(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
        )
        if validate:
            return RootModel[GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000Pydantic, raw_response.body)


class ApiForpatch(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apatch(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_event_mapped_args(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
        )
        return await self._aupdate_event_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def patch(
        self,
        id: str,
        due_date: typing.Optional[date] = None,
        feedback_given_date: typing.Optional[date] = None,
        feedback_creation_date: typing.Optional[date] = None,
        requested_by: typing.Optional[RequestedByD396fd5bffec1000100f44a5808f0006] = None,
        about_worker: typing.Optional[AboutWorkerD396fd5bffec1000100f44a5808f0005] = None,
        expiration_date: typing.Optional[date] = None,
        display_nameof_responder: typing.Optional[bool] = None,
        feedback_comments: typing.Optional[typing.List[RequestedFeedbackCommentsD396fd5bffec10001393477e77870000]] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersD396fd5bffec1000100f440bde4c0001] = None,
        feedback_private: typing.Optional[bool] = None,
        feedback_confidential: typing.Optional[bool] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_event_mapped_args(
            body=body,
            id=id,
            due_date=due_date,
            feedback_given_date=feedback_given_date,
            feedback_creation_date=feedback_creation_date,
            requested_by=requested_by,
            about_worker=about_worker,
            expiration_date=expiration_date,
            display_nameof_responder=display_nameof_responder,
            feedback_comments=feedback_comments,
            business_process_parameters=business_process_parameters,
            feedback_private=feedback_private,
            feedback_confidential=feedback_confidential,
            id=id,
            descriptor=descriptor,
        )
        return self._update_event_oapg(
            body=args.body,
            path_params=args.path,
        )

