# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.associated_reviews_summary2c793e888bcd1000346e381955dd0000 import AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000
from workday_performance_enablement_python_sdk import configuration


class TestAssociatedReviewsSummary2c793e888bcd1000346e381955dd0000(unittest.TestCase):
    """AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
