# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.person_data_view_be343791f59d100028d6a277ca8a0017 import PersonDataViewBe343791f59d100028d6a277ca8a0017
from workday_performance_enablement_python_sdk import configuration


class TestPersonDataViewBe343791f59d100028d6a277ca8a0017(unittest.TestCase):
    """PersonDataViewBe343791f59d100028d6a277ca8a0017 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
