# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.question_multiple_choice_ffdd5de32f7f100016c2c1e768f40000 import QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000
from workday_performance_enablement_python_sdk import configuration


class TestQuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000(unittest.TestCase):
    """QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
