# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.comments86093b8a932f10001499f356ff83012e import Comments86093b8a932f10001499f356ff83012e
from workday_performance_enablement_python_sdk import configuration


class TestComments86093b8a932f10001499f356ff83012e(unittest.TestCase):
    """Comments86093b8a932f10001499f356ff83012e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
