# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.primary_job352c3a97ecd51000353cba144c5b0042 import PrimaryJob352c3a97ecd51000353cba144c5b0042
from workday_performance_enablement_python_sdk import configuration


class TestPrimaryJob352c3a97ecd51000353cba144c5b0042(unittest.TestCase):
    """PrimaryJob352c3a97ecd51000353cba144c5b0042 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
