# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.category43b30ba735b8100011ee4781a9d50146 import Category43b30ba735b8100011ee4781a9d50146
from workday_performance_enablement_python_sdk import configuration


class TestCategory43b30ba735b8100011ee4781a9d50146(unittest.TestCase):
    """Category43b30ba735b8100011ee4781a9d50146 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
