# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_template2b4c8a6ca069100035b859a141200001 import FeedbackTemplate2b4c8a6ca069100035b859a141200001
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackTemplate2b4c8a6ca069100035b859a141200001(unittest.TestCase):
    """FeedbackTemplate2b4c8a6ca069100035b859a141200001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
