# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.for5d688bd57bb910001815ab3dd10024a9 import For5d688bd57bb910001815ab3dd10024a9
from workday_performance_enablement_python_sdk import configuration


class TestFor5d688bd57bb910001815ab3dd10024a9(unittest.TestCase):
    """For5d688bd57bb910001815ab3dd10024a9 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
