# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.person86093b8a932f10001499f38c72410130 import Person86093b8a932f10001499f38c72410130
from workday_performance_enablement_python_sdk import configuration


class TestPerson86093b8a932f10001499f38c72410130(unittest.TestCase):
    """Person86093b8a932f10001499f38c72410130 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
