# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.worker_data_c2466b0778c610000d1936006720000e import WorkerDataC2466b0778c610000d1936006720000e
from workday_performance_enablement_python_sdk import configuration


class TestWorkerDataC2466b0778c610000d1936006720000e(unittest.TestCase):
    """WorkerDataC2466b0778c610000d1936006720000e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
