# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.from_worker_afd6ac52d62510001357f891ccfd0001 import FromWorkerAfd6ac52d62510001357f891ccfd0001
from workday_performance_enablement_python_sdk import configuration


class TestFromWorkerAfd6ac52d62510001357f891ccfd0001(unittest.TestCase):
    """FromWorkerAfd6ac52d62510001357f891ccfd0001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
