# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.relates_to_c836a10b43ed10000beb5b92b4c10000 import RelatesToC836a10b43ed10000beb5b92b4c10000
from workday_performance_enablement_python_sdk import configuration


class TestRelatesToC836a10b43ed10000beb5b92b4c10000(unittest.TestCase):
    """RelatesToC836a10b43ed10000beb5b92b4c10000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
