# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.event_attachments_for_toolbar43b30ba735b8100011ee4767246d0143 import EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143
from workday_performance_enablement_python_sdk import configuration


class TestEventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143(unittest.TestCase):
    """EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
