# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.business_process_parameters_d396fd5bffec1000100f440bde4c0001 import BusinessProcessParametersD396fd5bffec1000100f440bde4c0001
from workday_performance_enablement_python_sdk import configuration


class TestBusinessProcessParametersD396fd5bffec1000100f440bde4c0001(unittest.TestCase):
    """BusinessProcessParametersD396fd5bffec1000100f440bde4c0001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
