# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.gig_opening_talent_tag_abe398d81e1e1000167d6197a9060000 import GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000
from workday_performance_enablement_python_sdk import configuration


class TestGigOpeningTalentTagAbe398d81e1e1000167d6197a9060000(unittest.TestCase):
    """GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
