# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.question_type544916c1cd75100006c4f105d3f60000 import QuestionType544916c1cd75100006c4f105d3f60000
from workday_performance_enablement_python_sdk import configuration


class TestQuestionType544916c1cd75100006c4f105d3f60000(unittest.TestCase):
    """QuestionType544916c1cd75100006c4f105d3f60000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
