# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.country_af21e47ff7c01000092ecf4d7ad30270 import CountryAf21e47ff7c01000092ecf4d7ad30270
from workday_performance_enablement_python_sdk import configuration


class TestCountryAf21e47ff7c01000092ecf4d7ad30270(unittest.TestCase):
    """CountryAf21e47ff7c01000092ecf4d7ad30270 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
