# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.goals_summary2c793e888bcd100033e663075a2b0000 import GoalsSummary2c793e888bcd100033e663075a2b0000
from workday_performance_enablement_python_sdk import configuration


class TestGoalsSummary2c793e888bcd100033e663075a2b0000(unittest.TestCase):
    """GoalsSummary2c793e888bcd100033e663075a2b0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
