# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_about2b4c8a6ca069100035b85907ae2c0002 import FeedbackAbout2b4c8a6ca069100035b85907ae2c0002
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackAbout2b4c8a6ca069100035b85907ae2c0002(unittest.TestCase):
    """FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
