# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.job_type_b8ac205877fd10000ea91752f39c00ab import JobTypeB8ac205877fd10000ea91752f39c00ab
from workday_performance_enablement_python_sdk import configuration


class TestJobTypeB8ac205877fd10000ea91752f39c00ab(unittest.TestCase):
    """JobTypeB8ac205877fd10000ea91752f39c00ab unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
