# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.job_data_for_worker_b8ac205877fd10000ea91719a02a00a2 import JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
from workday_performance_enablement_python_sdk import configuration


class TestJobDataForWorkerB8ac205877fd10000ea91719a02a00a2(unittest.TestCase):
    """JobDataForWorkerB8ac205877fd10000ea91719a02a00a2 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
