# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.requested_feedback_question_ffdd5de32f7f1000144df0c21e640000 import RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
from workday_performance_enablement_python_sdk import configuration


class TestRequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000(unittest.TestCase):
    """RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
