# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.get_workers_feedback_also_about3ab333661034100010b5635b2f7a0302 import GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302
from workday_performance_enablement_python_sdk import configuration


class TestGetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302(unittest.TestCase):
    """GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
