# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.status9df8579a128710001ac8e9879d1f0001 import Status9df8579a128710001ac8e9879d1f0001
from workday_performance_enablement_python_sdk import configuration


class TestStatus9df8579a128710001ac8e9879d1f0001(unittest.TestCase):
    """Status9df8579a128710001ac8e9879d1f0001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
