# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.question_type_ffdd5de32f7f1000144df15bb77b0001 import QuestionTypeFfdd5de32f7f1000144df15bb77b0001
from workday_performance_enablement_python_sdk import configuration


class TestQuestionTypeFfdd5de32f7f1000144df15bb77b0001(unittest.TestCase):
    """QuestionTypeFfdd5de32f7f1000144df15bb77b0001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
