# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.workers_get_self_requested_feedback_response import WorkersGetSelfRequestedFeedbackResponse
from workday_performance_enablement_python_sdk import configuration


class TestWorkersGetSelfRequestedFeedbackResponse(unittest.TestCase):
    """WorkersGetSelfRequestedFeedbackResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
