# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.overall_business_process5d688bd57bb910001815ab49927724aa import OverallBusinessProcess5d688bd57bb910001815ab49927724aa
from workday_performance_enablement_python_sdk import configuration


class TestOverallBusinessProcess5d688bd57bb910001815ab49927724aa(unittest.TestCase):
    """OverallBusinessProcess5d688bd57bb910001815ab49927724aa unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
