# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.requested_feedback_on_worker_event_detail2b4c8a6ca069100035b8586e16c20000 import RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000
from workday_performance_enablement_python_sdk import configuration


class TestRequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000(unittest.TestCase):
    """RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
