# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_badge_icon_d4d355b2d3db100020b8608b75250016 import FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackBadgeIconD4d355b2d3db100020b8608b75250016(unittest.TestCase):
    """FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
