# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.job_workspace_data1005157e3d631000144205466a6c13d3 import JobWorkspaceData1005157e3d631000144205466a6c13d3
from workday_performance_enablement_python_sdk import configuration


class TestJobWorkspaceData1005157e3d631000144205466a6c13d3(unittest.TestCase):
    """JobWorkspaceData1005157e3d631000144205466a6c13d3 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
