# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.workers_to_notify9e478586f65410001035b6c26a4c0000 import WorkersToNotify9e478586f65410001035b6c26a4c0000
from workday_performance_enablement_python_sdk import configuration


class TestWorkersToNotify9e478586f65410001035b6c26a4c0000(unittest.TestCase):
    """WorkersToNotify9e478586f65410001035b6c26a4c0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
