# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.content_type43b30ba735b8100011ee47993f11014a import ContentType43b30ba735b8100011ee47993f11014a
from workday_performance_enablement_python_sdk import configuration


class TestContentType43b30ba735b8100011ee47993f11014a(unittest.TestCase):
    """ContentType43b30ba735b8100011ee47993f11014a unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
