# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.country_data_for_location_data_af21e47ff7c01000092e0e4f9a22026e import CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e
from workday_performance_enablement_python_sdk import configuration


class TestCountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e(unittest.TestCase):
    """CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
