# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.business_process_parameters_afd6ac52d6251000117d0a60ed8b0000 import BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
from workday_performance_enablement_python_sdk import configuration


class TestBusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000(unittest.TestCase):
    """BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
