# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.about_worker_d396fd5bffec1000100f44a5808f0005 import AboutWorkerD396fd5bffec1000100f44a5808f0005
from workday_performance_enablement_python_sdk import configuration


class TestAboutWorkerD396fd5bffec1000100f44a5808f0005(unittest.TestCase):
    """AboutWorkerD396fd5bffec1000100f44a5808f0005 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
