# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_template4db9c44d36231000134c7b8eb3800000 import FeedbackTemplate4db9c44d36231000134c7b8eb3800000
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackTemplate4db9c44d36231000134c7b8eb3800000(unittest.TestCase):
    """FeedbackTemplate4db9c44d36231000134c7b8eb3800000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
