# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.supervisory_organization_b8ac205877fd10000ea91743659800a7 import SupervisoryOrganizationB8ac205877fd10000ea91743659800a7
from workday_performance_enablement_python_sdk import configuration


class TestSupervisoryOrganizationB8ac205877fd10000ea91743659800a7(unittest.TestCase):
    """SupervisoryOrganizationB8ac205877fd10000ea91743659800a7 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
