# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.worker47e98fa91eee100017c2c78c80410000 import Worker47e98fa91eee100017c2c78c80410000
from workday_performance_enablement_python_sdk import configuration


class TestWorker47e98fa91eee100017c2c78c80410000(unittest.TestCase):
    """Worker47e98fa91eee100017c2c78c80410000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
