# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.action38ff08ab6736100010816009079d0126 import Action38ff08ab6736100010816009079d0126
from workday_performance_enablement_python_sdk import configuration


class TestAction38ff08ab6736100010816009079d0126(unittest.TestCase):
    """Action38ff08ab6736100010816009079d0126 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
