# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.category_summary88d272af423b100036e57ea69d570000 import CategorySummary88d272af423b100036e57ea69d570000
from workday_performance_enablement_python_sdk import configuration


class TestCategorySummary88d272af423b100036e57ea69d570000(unittest.TestCase):
    """CategorySummary88d272af423b100036e57ea69d570000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
