# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.business_process_parameters9708c966f04f10000e4ae9a03cf80001 import BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001
from workday_performance_enablement_python_sdk import configuration


class TestBusinessProcessParameters9708c966f04f10000e4ae9a03cf80001(unittest.TestCase):
    """BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
