# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.business_process_parameters2b4c8a6ca069100035b85907ae2c0000 import BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000
from workday_performance_enablement_python_sdk import configuration


class TestBusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000(unittest.TestCase):
    """BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
