# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_badge_detail9eab868ca81410001402525d054211f7 import FeedbackBadgeDetail9eab868ca81410001402525d054211f7
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackBadgeDetail9eab868ca81410001402525d054211f7(unittest.TestCase):
    """FeedbackBadgeDetail9eab868ca81410001402525d054211f7 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
