# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 import GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000
from workday_performance_enablement_python_sdk import configuration


class TestGiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000(unittest.TestCase):
    """GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
