# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.worker_type3f78eeedc01d1000138d97d80e5a0000 import WorkerType3f78eeedc01d1000138d97d80e5a0000
from workday_performance_enablement_python_sdk import configuration


class TestWorkerType3f78eeedc01d1000138d97d80e5a0000(unittest.TestCase):
    """WorkerType3f78eeedc01d1000138d97d80e5a0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
