# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_response2f703c317dc910001bd2de83d1590000 import FeedbackResponse2f703c317dc910001bd2de83d1590000
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackResponse2f703c317dc910001bd2de83d1590000(unittest.TestCase):
    """FeedbackResponse2f703c317dc910001bd2de83d1590000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
