# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.work_space426ac445037110001b3eb91ddf6f0100 import WorkSpace426ac445037110001b3eb91ddf6f0100
from workday_performance_enablement_python_sdk import configuration


class TestWorkSpace426ac445037110001b3eb91ddf6f0100(unittest.TestCase):
    """WorkSpace426ac445037110001b3eb91ddf6f0100 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
