# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.person0ad147648b0a1000237bd486634a001a import Person0ad147648b0a1000237bd486634a001a
from workday_performance_enablement_python_sdk import configuration


class TestPerson0ad147648b0a1000237bd486634a001a(unittest.TestCase):
    """Person0ad147648b0a1000237bd486634a001a unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
