# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.multiple_choice_answers06c0300303a9100019828d5ca44a0000 import MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000
from workday_performance_enablement_python_sdk import configuration


class TestMultipleChoiceAnswers06c0300303a9100019828d5ca44a0000(unittest.TestCase):
    """MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
