# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.to_worker_f4946919a39f10000f03207b1f230000 import ToWorkerF4946919a39f10000f03207b1f230000
from workday_performance_enablement_python_sdk import configuration


class TestToWorkerF4946919a39f10000f03207b1f230000(unittest.TestCase):
    """ToWorkerF4946919a39f10000f03207b1f230000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
