# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_event_detail_afd6ac52d62510001086b5c85cd50000 import FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackEventDetailAfd6ac52d62510001086b5c85cd50000(unittest.TestCase):
    """FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
