# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.activity_streamable_item_summary88d272af423b100036fc19a90e210000 import ActivityStreamableItemSummary88d272af423b100036fc19a90e210000
from workday_performance_enablement_python_sdk import configuration


class TestActivityStreamableItemSummary88d272af423b100036fc19a90e210000(unittest.TestCase):
    """ActivityStreamableItemSummary88d272af423b100036fc19a90e210000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
