# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.created_by88d272af423b100036b561a7784b0000 import CreatedBy88d272af423b100036b561a7784b0000
from workday_performance_enablement_python_sdk import configuration


class TestCreatedBy88d272af423b100036b561a7784b0000(unittest.TestCase):
    """CreatedBy88d272af423b100036b561a7784b0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
