# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.requested_feedback_on_self_event_detail19acce0101b310002e6bf03e1bbc0000 import RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000
from workday_performance_enablement_python_sdk import configuration


class TestRequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000(unittest.TestCase):
    """RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
