# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.workers_get_collection_staffing_response import WorkersGetCollectionStaffingResponse
from workday_performance_enablement_python_sdk import configuration


class TestWorkersGetCollectionStaffingResponse(unittest.TestCase):
    """WorkersGetCollectionStaffingResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
