# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.job_profile_b8ac205877fd10000ea9174f73c500aa import JobProfileB8ac205877fd10000ea9174f73c500aa
from workday_performance_enablement_python_sdk import configuration


class TestJobProfileB8ac205877fd10000ea9174f73c500aa(unittest.TestCase):
    """JobProfileB8ac205877fd10000ea9174f73c500aa unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
