# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.supervisory_organization_job_view_fab4a151b24810000d29746fb7e21259 import SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259
from workday_performance_enablement_python_sdk import configuration


class TestSupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259(unittest.TestCase):
    """SupervisoryOrganizationJobViewFab4a151b24810000d29746fb7e21259 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
