# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_responder2f703c317dc910001c16504848720001 import FeedbackResponder2f703c317dc910001c16504848720001
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackResponder2f703c317dc910001c16504848720001(unittest.TestCase):
    """FeedbackResponder2f703c317dc910001c16504848720001 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
