# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import unittest

import workday_performance_enablement_python_sdk
from workday_performance_enablement_python_sdk.model.feedback_about4db9c44d36231000134c7b8eb3800003 import FeedbackAbout4db9c44d36231000134c7b8eb3800003
from workday_performance_enablement_python_sdk import configuration


class TestFeedbackAbout4db9c44d36231000134c7b8eb3800003(unittest.TestCase):
    """FeedbackAbout4db9c44d36231000134c7b8eb3800003 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
