# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from workday_performance_enablement_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from workday_performance_enablement_python_sdk.api_response import AsyncGeneratorResponse
from workday_performance_enablement_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_performance_enablement_python_sdk import schemas  # noqa: F401

from workday_performance_enablement_python_sdk.model.feedback_event_detail_afd6ac52d62510001086b5c85cd50000 import FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 as FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Schema
from workday_performance_enablement_python_sdk.model.related_feedback_events9708c966f04f10000e1e9b7f9a5c0000 import RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000 as RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000Schema
from workday_performance_enablement_python_sdk.model.relates_to9d12ad407f0f10001c3949add7d40000 import RelatesTo9d12ad407f0f10001c3949add7d40000 as RelatesTo9d12ad407f0f10001c3949add7d40000Schema
from workday_performance_enablement_python_sdk.model.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCESchema
from workday_performance_enablement_python_sdk.model.from_worker_afd6ac52d62510001357f891ccfd0001 import FromWorkerAfd6ac52d62510001357f891ccfd0001 as FromWorkerAfd6ac52d62510001357f891ccfd0001Schema
from workday_performance_enablement_python_sdk.model.business_process_parameters_afd6ac52d6251000117d0a60ed8b0000 import BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 as BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000Schema
from workday_performance_enablement_python_sdk.model.badge_afd6ac52d62510001357f891ccfd0003 import BadgeAfd6ac52d62510001357f891ccfd0003 as BadgeAfd6ac52d62510001357f891ccfd0003Schema
from workday_performance_enablement_python_sdk.model.get_workers_feedback_also_about3ab333661034100010b5635b2f7a0302 import GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 as GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302Schema
from workday_performance_enablement_python_sdk.model.to_worker_f4946919a39f10000f03207b1f230000 import ToWorkerF4946919a39f10000f03207b1f230000 as ToWorkerF4946919a39f10000f03207b1f230000Schema
from workday_performance_enablement_python_sdk.model.workers_to_notify9e478586f65410001035b6c26a4c0000 import WorkersToNotify9e478586f65410001035b6c26a4c0000 as WorkersToNotify9e478586f65410001035b6c26a4c0000Schema
from workday_performance_enablement_python_sdk.model.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCESchema

from workday_performance_enablement_python_sdk.type.to_worker_f4946919a39f10000f03207b1f230000 import ToWorkerF4946919a39f10000f03207b1f230000
from workday_performance_enablement_python_sdk.type.get_workers_feedback_also_about3ab333661034100010b5635b2f7a0302 import GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302
from workday_performance_enablement_python_sdk.type.badge_afd6ac52d62510001357f891ccfd0003 import BadgeAfd6ac52d62510001357f891ccfd0003
from workday_performance_enablement_python_sdk.type.business_process_parameters_afd6ac52d6251000117d0a60ed8b0000 import BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000
from workday_performance_enablement_python_sdk.type.errormodelreference import ERRORMODELREFERENCE
from workday_performance_enablement_python_sdk.type.from_worker_afd6ac52d62510001357f891ccfd0001 import FromWorkerAfd6ac52d62510001357f891ccfd0001
from workday_performance_enablement_python_sdk.type.workers_to_notify9e478586f65410001035b6c26a4c0000 import WorkersToNotify9e478586f65410001035b6c26a4c0000
from workday_performance_enablement_python_sdk.type.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE
from workday_performance_enablement_python_sdk.type.related_feedback_events9708c966f04f10000e1e9b7f9a5c0000 import RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000
from workday_performance_enablement_python_sdk.type.relates_to9d12ad407f0f10001c3949add7d40000 import RelatesTo9d12ad407f0f10001c3949add7d40000
from workday_performance_enablement_python_sdk.type.feedback_event_detail_afd6ac52d62510001086b5c85cd50000 import FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000

from ...api_client import Dictionary
from workday_performance_enablement_python_sdk.pydantic.errormodelreference import ERRORMODELREFERENCE as ERRORMODELREFERENCEPydantic
from workday_performance_enablement_python_sdk.pydantic.relates_to9d12ad407f0f10001c3949add7d40000 import RelatesTo9d12ad407f0f10001c3949add7d40000 as RelatesTo9d12ad407f0f10001c3949add7d40000Pydantic
from workday_performance_enablement_python_sdk.pydantic.business_process_parameters_afd6ac52d6251000117d0a60ed8b0000 import BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 as BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000Pydantic
from workday_performance_enablement_python_sdk.pydantic.from_worker_afd6ac52d62510001357f891ccfd0001 import FromWorkerAfd6ac52d62510001357f891ccfd0001 as FromWorkerAfd6ac52d62510001357f891ccfd0001Pydantic
from workday_performance_enablement_python_sdk.pydantic.feedback_event_detail_afd6ac52d62510001086b5c85cd50000 import FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 as FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic
from workday_performance_enablement_python_sdk.pydantic.to_worker_f4946919a39f10000f03207b1f230000 import ToWorkerF4946919a39f10000f03207b1f230000 as ToWorkerF4946919a39f10000f03207b1f230000Pydantic
from workday_performance_enablement_python_sdk.pydantic.badge_afd6ac52d62510001357f891ccfd0003 import BadgeAfd6ac52d62510001357f891ccfd0003 as BadgeAfd6ac52d62510001357f891ccfd0003Pydantic
from workday_performance_enablement_python_sdk.pydantic.related_feedback_events9708c966f04f10000e1e9b7f9a5c0000 import RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000 as RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000Pydantic
from workday_performance_enablement_python_sdk.pydantic.workers_to_notify9e478586f65410001035b6c26a4c0000 import WorkersToNotify9e478586f65410001035b6c26a4c0000 as WorkersToNotify9e478586f65410001035b6c26a4c0000Pydantic
from workday_performance_enablement_python_sdk.pydantic.get_workers_feedback_also_about3ab333661034100010b5635b2f7a0302 import GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 as GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302Pydantic
from workday_performance_enablement_python_sdk.pydantic.validationerrormodelreference import VALIDATIONERRORMODELREFERENCE as VALIDATIONERRORMODELREFERENCEPydantic

# Path params
IDSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'ID': typing.Union[IDSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_id = api_client.PathParameter(
    name="ID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IDSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Schema


request_body_feedback_event_detail_afd6ac52d62510001086b5c85cd50000 = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Schema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = VALIDATIONERRORMODELREFERENCESchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: VALIDATIONERRORMODELREFERENCE


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = ERRORMODELREFERENCESchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ERRORMODELREFERENCE


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ERRORMODELREFERENCE


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_feedback_event_mapped_args(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if to_worker is not None:
            _body["toWorker"] = to_worker
        if workers_to_notify is not None:
            _body["workersToNotify"] = workers_to_notify
        if relates_to is not None:
            _body["relatesTo"] = relates_to
        if business_process_parameters is not None:
            _body["businessProcessParameters"] = business_process_parameters
        if feedback_also_about is not None:
            _body["feedbackAlsoAbout"] = feedback_also_about
        if hidden_from_worker is not None:
            _body["hiddenFromWorker"] = hidden_from_worker
        if hidden_from_manager is not None:
            _body["hiddenFromManager"] = hidden_from_manager
        if comment is not None:
            _body["comment"] = comment
        if from_worker is not None:
            _body["fromWorker"] = from_worker
        if badge is not None:
            _body["badge"] = badge
        if related_feedback_events is not None:
            _body["relatedFeedbackEvents"] = related_feedback_events
        if feedback_given_date is not None:
            _body["feedbackGivenDate"] = feedback_given_date
        if show_feedback_provider_name is not None:
            _body["showFeedbackProviderName"] = show_feedback_provider_name
        if href is not None:
            _body["href"] = href
        if id is not None:
            _body["id"] = id
        if descriptor is not None:
            _body["descriptor"] = descriptor
        args.body = _body
        if id is not None:
            _path_params["ID"] = id
        args.path = _path_params
        return args

    async def _acreate_feedback_event_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Creates a single feedback given event instance about the specified worker.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/workers/{ID}/anytimeFeedbackEvents',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_feedback_event_detail_afd6ac52d62510001086b5c85cd50000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_feedback_event_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Creates a single feedback given event instance about the specified worker.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/workers/{ID}/anytimeFeedbackEvents',
            body=body,
            headers=_headers,
        )
        serialized_data = request_body_feedback_event_detail_afd6ac52d62510001086b5c85cd50000.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateFeedbackEventRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_feedback_event(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_feedback_event_mapped_args(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
        )
        return await self._acreate_feedback_event_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def create_feedback_event(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_feedback_event_mapped_args(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
        )
        return self._create_feedback_event_oapg(
            body=args.body,
            path_params=args.path,
        )

class CreateFeedbackEvent(BaseApi):

    async def acreate_feedback_event(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic:
        raw_response = await self.raw.acreate_feedback_event(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
            **kwargs,
        )
        if validate:
            return RootModel[FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic, raw_response.body)
    
    
    def create_feedback_event(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        validate: bool = False,
    ) -> FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic:
        raw_response = self.raw.create_feedback_event(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
        )
        if validate:
            return RootModel[FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic](raw_response.body).root
        return api_client.construct_model_instance(FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000Pydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_feedback_event_mapped_args(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
        )
        return await self._acreate_feedback_event_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        id: str,
        to_worker: typing.Optional[ToWorkerF4946919a39f10000f03207b1f230000] = None,
        workers_to_notify: typing.Optional[typing.List[WorkersToNotify9e478586f65410001035b6c26a4c0000]] = None,
        relates_to: typing.Optional[RelatesTo9d12ad407f0f10001c3949add7d40000] = None,
        business_process_parameters: typing.Optional[BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000] = None,
        feedback_also_about: typing.Optional[typing.List[GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302]] = None,
        hidden_from_worker: typing.Optional[bool] = None,
        hidden_from_manager: typing.Optional[bool] = None,
        comment: typing.Optional[str] = None,
        from_worker: typing.Optional[FromWorkerAfd6ac52d62510001357f891ccfd0001] = None,
        badge: typing.Optional[BadgeAfd6ac52d62510001357f891ccfd0003] = None,
        related_feedback_events: typing.Optional[typing.List[RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000]] = None,
        feedback_given_date: typing.Optional[date] = None,
        show_feedback_provider_name: typing.Optional[bool] = None,
        href: typing.Optional[str] = None,
        id: typing.Optional[str] = None,
        descriptor: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_feedback_event_mapped_args(
            body=body,
            id=id,
            to_worker=to_worker,
            workers_to_notify=workers_to_notify,
            relates_to=relates_to,
            business_process_parameters=business_process_parameters,
            feedback_also_about=feedback_also_about,
            hidden_from_worker=hidden_from_worker,
            hidden_from_manager=hidden_from_manager,
            comment=comment,
            from_worker=from_worker,
            badge=badge,
            related_feedback_events=related_feedback_events,
            feedback_given_date=feedback_given_date,
            show_feedback_provider_name=show_feedback_provider_name,
            href=href,
            id=id,
            descriptor=descriptor,
        )
        return self._create_feedback_event_oapg(
            body=args.body,
            path_params=args.path,
        )

