# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from workday_performance_enablement_python_sdk.paths.give_requested_feedback_events.get import GetCollectionFeedbackEvents
from workday_performance_enablement_python_sdk.paths.give_requested_feedback_events_id.get import GetInstance
from workday_performance_enablement_python_sdk.paths.give_requested_feedback_events_id.patch import UpdateEvent
from workday_performance_enablement_python_sdk.apis.tags.give_requested_feedback_events_api_raw import GiveRequestedFeedbackEventsApiRaw


class GiveRequestedFeedbackEventsApi(
    GetCollectionFeedbackEvents,
    GetInstance,
    UpdateEvent,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GiveRequestedFeedbackEventsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GiveRequestedFeedbackEventsApiRaw(api_client)
