# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from workday_performance_enablement_python_sdk.paths.values_workers_to_notify_workers_to_notify.get import GetInstancesRaw
from workday_performance_enablement_python_sdk.paths.values_feedback_template_feedback_template.get import GetInstances0Raw
from workday_performance_enablement_python_sdk.paths.values_feedback_on_worker_feedback_on_worker.get import GetInstances1Raw
from workday_performance_enablement_python_sdk.paths.values_feedback_responder_feedback_responder.get import GetInstances2Raw
from workday_performance_enablement_python_sdk.paths.values_relates_to_relates_to.get import GetInstances3Raw


class PromptValuesApiRaw(
    GetInstancesRaw,
    GetInstances0Raw,
    GetInstances1Raw,
    GetInstances2Raw,
    GetInstances3Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
