# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events.post import CreateFeedbackEvent
from workday_performance_enablement_python_sdk.paths.workers.get import GetCollectionStaffing
from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events_subresource_id.get import GetFeedbackEvent
from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events.get import GetFeedbackEvents
from workday_performance_enablement_python_sdk.paths.workers_id_goals.get import GetGoals
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events_subresource_id.get import GetRequestedEvent
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events.get import GetRequestedFeedbackEvents
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events.get import GetSelfRequestedFeedback
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events_subresource_id.get import GetSelfRequestedFeedbackEvent
from workday_performance_enablement_python_sdk.paths.workers_id_goals_subresource_id.get import GetSingleGoal
from workday_performance_enablement_python_sdk.paths.workers_id.get import GetStaffingInformation
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events.post import RequestFeedbackOnSelfEvents
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events.post import RequestFeedbackOnWorkerEvents
from workday_performance_enablement_python_sdk.apis.tags.workers_api_raw import WorkersApiRaw


class WorkersApi(
    CreateFeedbackEvent,
    GetCollectionStaffing,
    GetFeedbackEvent,
    GetFeedbackEvents,
    GetGoals,
    GetRequestedEvent,
    GetRequestedFeedbackEvents,
    GetSelfRequestedFeedback,
    GetSelfRequestedFeedbackEvent,
    GetSingleGoal,
    GetStaffingInformation,
    RequestFeedbackOnSelfEvents,
    RequestFeedbackOnWorkerEvents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkersApiRaw(api_client)
