# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events.post import CreateFeedbackEventRaw
from workday_performance_enablement_python_sdk.paths.workers.get import GetCollectionStaffingRaw
from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events_subresource_id.get import GetFeedbackEventRaw
from workday_performance_enablement_python_sdk.paths.workers_id_anytime_feedback_events.get import GetFeedbackEventsRaw
from workday_performance_enablement_python_sdk.paths.workers_id_goals.get import GetGoalsRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events_subresource_id.get import GetRequestedEventRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events.get import GetRequestedFeedbackEventsRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events.get import GetSelfRequestedFeedbackRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events_subresource_id.get import GetSelfRequestedFeedbackEventRaw
from workday_performance_enablement_python_sdk.paths.workers_id_goals_subresource_id.get import GetSingleGoalRaw
from workday_performance_enablement_python_sdk.paths.workers_id.get import GetStaffingInformationRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_self_events.post import RequestFeedbackOnSelfEventsRaw
from workday_performance_enablement_python_sdk.paths.workers_id_requested_feedback_on_worker_events.post import RequestFeedbackOnWorkerEventsRaw


class WorkersApiRaw(
    CreateFeedbackEventRaw,
    GetCollectionStaffingRaw,
    GetFeedbackEventRaw,
    GetFeedbackEventsRaw,
    GetGoalsRaw,
    GetRequestedEventRaw,
    GetRequestedFeedbackEventsRaw,
    GetSelfRequestedFeedbackRaw,
    GetSelfRequestedFeedbackEventRaw,
    GetSingleGoalRaw,
    GetStaffingInformationRaw,
    RequestFeedbackOnSelfEventsRaw,
    RequestFeedbackOnWorkerEventsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
