# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredFACETSMODELREFERENCEItemValuesItem(TypedDict):
    # wid / id / reference id
    id: str

class OptionalFACETSMODELREFERENCEItemValuesItem(TypedDict, total=False):
    # The number of instances returned by this facet
    count: int

    # A description of the facet
    descriptor: str

    # A link to the instance
    href: str

class FACETSMODELREFERENCEItemValuesItem(RequiredFACETSMODELREFERENCEItemValuesItem, OptionalFACETSMODELREFERENCEItemValuesItem):
    pass
