# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.facetsmodelreference_item_values import FACETSMODELREFERENCEItemValues

class RequiredFACETSMODELREFERENCEItem(TypedDict):
    pass

class OptionalFACETSMODELREFERENCEItem(TypedDict, total=False):
    # A description of the facet
    descriptor: str

    # The alias used to select the facet
    facetParameter: str

    values: FACETSMODELREFERENCEItemValues

class FACETSMODELREFERENCEItem(RequiredFACETSMODELREFERENCEItem, OptionalFACETSMODELREFERENCEItem):
    pass
