# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.about_worker_d396fd5bffec1000100f44a5808f0005 import AboutWorkerD396fd5bffec1000100f44a5808f0005
from workday_performance_enablement_python_sdk.type.business_process_parameters_d396fd5bffec1000100f440bde4c0001 import BusinessProcessParametersD396fd5bffec1000100f440bde4c0001
from workday_performance_enablement_python_sdk.type.requested_by_d396fd5bffec1000100f44a5808f0006 import RequestedByD396fd5bffec1000100f44a5808f0006
from workday_performance_enablement_python_sdk.type.requested_feedback_comments_d396fd5bffec10001393477e77870000 import RequestedFeedbackCommentsD396fd5bffec10001393477e77870000

GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
