# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.give_requested_feedback_details_d396fd5bffec10000e3eba1a70440000 import GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000

class RequiredGiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse(TypedDict):
    pass

class OptionalGiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse(TypedDict, total=False):
    data: typing.List[GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000]

    total: int

class GiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse(RequiredGiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse, OptionalGiveRequestedFeedbackEventsGetCollectionFeedbackEventsResponse):
    pass
