# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredINSTANCEMODELREFERENCE(TypedDict):
    # wid / id / reference id
    id: str

class OptionalINSTANCEMODELREFERENCE(TypedDict, total=False):
    # A description of the instance
    descriptor: str

    # A link to the instance
    href: str

class INSTANCEMODELREFERENCE(RequiredINSTANCEMODELREFERENCE, OptionalINSTANCEMODELREFERENCE):
    pass
