# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.job_profile_job_view_fab4a151b24810000d511d61ee641262 import JobProfileJobViewFab4a151b24810000d511d61ee641262

JobProfileB8ac205877fd10000ea9174f73c500aa = typing.Union[JobProfileJobViewFab4a151b24810000d511d61ee641262,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
