# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.job_type_data_b8ac205877fd100005c3b50b74a30055 import JobTypeDataB8ac205877fd100005c3b50b74a30055

JobTypeB8ac205877fd10000ea91752f39c00ab = typing.Union[JobTypeDataB8ac205877fd100005c3b50b74a30055,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
