# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.gig_opening_talent_tag_abe398d81e1e1000167d6197a9060000 import GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000

RelatesTo9d12ad407f0f10001c3949add7d40000 = typing.Union[GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
