# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.goals_summary2c793e888bcd100033e663075a2b0000 import GoalsSummary2c793e888bcd100033e663075a2b0000

class RequiredWorkersGetGoalsResponse(TypedDict):
    pass

class OptionalWorkersGetGoalsResponse(TypedDict, total=False):
    data: typing.List[GoalsSummary2c793e888bcd100033e663075a2b0000]

    total: int

class WorkersGetGoalsResponse(RequiredWorkersGetGoalsResponse, OptionalWorkersGetGoalsResponse):
    pass
