# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.requested_feedback_on_self_event_detail19acce0101b310002e6bf03e1bbc0000 import RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000

class RequiredWorkersGetSelfRequestedFeedbackResponse(TypedDict):
    pass

class OptionalWorkersGetSelfRequestedFeedbackResponse(TypedDict, total=False):
    data: typing.List[RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000]

    total: int

class WorkersGetSelfRequestedFeedbackResponse(RequiredWorkersGetSelfRequestedFeedbackResponse, OptionalWorkersGetSelfRequestedFeedbackResponse):
    pass
