# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from workday_performance_enablement_python_sdk.type.worker_data_c2466b0778c610000d1936006720000e import WorkerDataC2466b0778c610000d1936006720000e

class RequiredWorkersGetCollectionStaffingResponse(TypedDict):
    pass

class OptionalWorkersGetCollectionStaffingResponse(TypedDict, total=False):
    data: typing.List[WorkerDataC2466b0778c610000d1936006720000e]

    total: int

class WorkersGetCollectionStaffingResponse(RequiredWorkersGetCollectionStaffingResponse, OptionalWorkersGetCollectionStaffingResponse):
    pass
