# coding: utf-8
"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from workday_performance_enablement_python_sdk.client_custom import ClientCustom
from workday_performance_enablement_python_sdk.configuration import Configuration
from workday_performance_enablement_python_sdk.api_client import ApiClient
from workday_performance_enablement_python_sdk.type_util import copy_signature
from workday_performance_enablement_python_sdk.apis.tags.prompt_values_api import PromptValuesApi
from workday_performance_enablement_python_sdk.apis.tags.feedback_badges_api import FeedbackBadgesApi
from workday_performance_enablement_python_sdk.apis.tags.give_requested_feedback_events_api import GiveRequestedFeedbackEventsApi
from workday_performance_enablement_python_sdk.apis.tags.workers_api import WorkersApi



class WorkdayPerformanceEnablement(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.prompt_values: PromptValuesApi = PromptValuesApi(api_client)
        self.feedback_badges: FeedbackBadgesApi = FeedbackBadgesApi(api_client)
        self.give_requested_feedback_events: GiveRequestedFeedbackEventsApi = GiveRequestedFeedbackEventsApi(api_client)
        self.workers: WorkersApi = WorkersApi(api_client)
