# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_performance_enablement_python_sdk.pydantic.feedback_badge_detail9eab868ca81410001402525d054211f7 import FeedbackBadgeDetail9eab868ca81410001402525d054211f7

class FeedbackBadgesGetCollectionResponse(BaseModel):
    data: typing.Optional[typing.List[FeedbackBadgeDetail9eab868ca81410001402525d054211f7]] = Field(None, alias='data')

    total: typing.Optional[int] = Field(None, alias='total')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
