# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_performance_enablement_python_sdk.pydantic.person_data_view_be343791f59d100028d6a277ca8a0017 import PersonDataViewBe343791f59d100028d6a277ca8a0017

Person0ad147648b0a1000237bd486634a001a = typing.Union[PersonDataViewBe343791f59d100028d6a277ca8a0017,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
