# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_performance_enablement_python_sdk.pydantic.feedback_question_d396fd5bffec10001393481822cd0007 import FeedbackQuestionD396fd5bffec10001393481822cd0007
from workday_performance_enablement_python_sdk.pydantic.multiple_choice_answers06c0300303a9100019828d5ca44a0000 import MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000
from workday_performance_enablement_python_sdk.pydantic.possible_multiple_choice_answers4c60c128c16510000a59980041610000 import PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000
from workday_performance_enablement_python_sdk.pydantic.question_type544916c1cd75100006c4f105d3f60000 import QuestionType544916c1cd75100006c4f105d3f60000
from workday_performance_enablement_python_sdk.pydantic.relates_to_c836a10b43ed10000beb5b92b4c10000 import RelatesToC836a10b43ed10000beb5b92b4c10000

RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
