# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from workday_performance_enablement_python_sdk.pydantic.business_process_parameters4db9c44d36231000134c7a5b6f3b0000 import BusinessProcessParameters4db9c44d36231000134c7a5b6f3b0000
from workday_performance_enablement_python_sdk.pydantic.feedback_about4db9c44d36231000134c7b8eb3800003 import FeedbackAbout4db9c44d36231000134c7b8eb3800003
from workday_performance_enablement_python_sdk.pydantic.feedback_responders_ffdd5de32f7f100016dbb1b188d70000 import FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000
from workday_performance_enablement_python_sdk.pydantic.feedback_template4db9c44d36231000134c7b8eb3800000 import FeedbackTemplate4db9c44d36231000134c7b8eb3800000
from workday_performance_enablement_python_sdk.pydantic.requested_feedback_question_ffdd5de32f7f1000144df0c21e640000 import RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000

RequestedFeedbackOnSelfEventDetail19acce0101b310002e6bf03e1bbc0000 = typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
