# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_performance_enablement_python_sdk import schemas  # noqa: F401


class FACETSMODELREFERENCEItemValues(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    the facet values
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['FACETSMODELREFERENCEItemValuesItem']:
            return FACETSMODELREFERENCEItemValuesItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['FACETSMODELREFERENCEItemValuesItem'], typing.List['FACETSMODELREFERENCEItemValuesItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'FACETSMODELREFERENCEItemValues':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'FACETSMODELREFERENCEItemValuesItem':
        return super().__getitem__(i)

from workday_performance_enablement_python_sdk.model.facetsmodelreference_item_values_item import FACETSMODELREFERENCEItemValuesItem
