# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_performance_enablement_python_sdk import schemas  # noqa: F401


class FeedbackBadgeDetail9eab868ca81410001402525d054211f7(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                
                    @staticmethod
                    def feedbackBadgeIcon() -> typing.Type['FeedbackBadgeIconD4d355b2d3db100020b8608b75250016']:
                        return FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
                    
                    
                    class workdayID(
                        schemas.StrSchema
                    ):
                    
                    
                        class MetaOapg:
                            max_length = 36
                    feedbackBadgeID = schemas.StrSchema
                    name = schemas.StrSchema
                    __annotations__ = {
                        "feedbackBadgeIcon": feedbackBadgeIcon,
                        "workdayID": workdayID,
                        "feedbackBadgeID": feedbackBadgeID,
                        "name": name,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["feedbackBadgeIcon"]) -> 'FeedbackBadgeIconD4d355b2d3db100020b8608b75250016': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["workdayID"]) -> MetaOapg.properties.workdayID: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["feedbackBadgeID"]) -> MetaOapg.properties.feedbackBadgeID: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["feedbackBadgeIcon", "workdayID", "feedbackBadgeID", "name", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["feedbackBadgeIcon"]) -> typing.Union['FeedbackBadgeIconD4d355b2d3db100020b8608b75250016', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["workdayID"]) -> typing.Union[MetaOapg.properties.workdayID, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["feedbackBadgeID"]) -> typing.Union[MetaOapg.properties.feedbackBadgeID, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["feedbackBadgeIcon", "workdayID", "feedbackBadgeID", "name", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                feedbackBadgeIcon: typing.Union['FeedbackBadgeIconD4d355b2d3db100020b8608b75250016', schemas.Unset] = schemas.unset,
                workdayID: typing.Union[MetaOapg.properties.workdayID, str, schemas.Unset] = schemas.unset,
                feedbackBadgeID: typing.Union[MetaOapg.properties.feedbackBadgeID, str, schemas.Unset] = schemas.unset,
                name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    feedbackBadgeIcon=feedbackBadgeIcon,
                    workdayID=workdayID,
                    feedbackBadgeID=feedbackBadgeID,
                    name=name,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FeedbackBadgeDetail9eab868ca81410001402525d054211f7':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_performance_enablement_python_sdk.model.feedback_badge_icon_d4d355b2d3db100020b8608b75250016 import FeedbackBadgeIconD4d355b2d3db100020b8608b75250016
