# coding: utf-8

"""
    performanceEnablement

    The Performance Management service enables applications to access and create feedback about workers in the system.

    The version of the OpenAPI document: v5
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from workday_performance_enablement_python_sdk import schemas  # noqa: F401


class FeedbackResponse2f703c317dc910001bd2de83d1590000(
    schemas.ComposedSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        
        class all_of_0(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    response = schemas.StrSchema
                    feedbackDeclined = schemas.BoolSchema
                    feedbackDeclineReason = schemas.StrSchema
                
                    @staticmethod
                    def feedbackResponder() -> typing.Type['FeedbackResponder2f703c317dc910001c16504848720001']:
                        return FeedbackResponder2f703c317dc910001c16504848720001
                    descriptor = schemas.StrSchema
                    id = schemas.StrSchema
                    __annotations__ = {
                        "response": response,
                        "feedbackDeclined": feedbackDeclined,
                        "feedbackDeclineReason": feedbackDeclineReason,
                        "feedbackResponder": feedbackResponder,
                        "descriptor": descriptor,
                        "id": id,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["response"]) -> MetaOapg.properties.response: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["feedbackDeclined"]) -> MetaOapg.properties.feedbackDeclined: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["feedbackDeclineReason"]) -> MetaOapg.properties.feedbackDeclineReason: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["feedbackResponder"]) -> 'FeedbackResponder2f703c317dc910001c16504848720001': ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["descriptor"]) -> MetaOapg.properties.descriptor: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["response", "feedbackDeclined", "feedbackDeclineReason", "feedbackResponder", "descriptor", "id", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["response"]) -> typing.Union[MetaOapg.properties.response, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["feedbackDeclined"]) -> typing.Union[MetaOapg.properties.feedbackDeclined, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["feedbackDeclineReason"]) -> typing.Union[MetaOapg.properties.feedbackDeclineReason, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["feedbackResponder"]) -> typing.Union['FeedbackResponder2f703c317dc910001c16504848720001', schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["descriptor"]) -> typing.Union[MetaOapg.properties.descriptor, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["response", "feedbackDeclined", "feedbackDeclineReason", "feedbackResponder", "descriptor", "id", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict.frozendict, ],
                response: typing.Union[MetaOapg.properties.response, str, schemas.Unset] = schemas.unset,
                feedbackDeclined: typing.Union[MetaOapg.properties.feedbackDeclined, bool, schemas.Unset] = schemas.unset,
                feedbackDeclineReason: typing.Union[MetaOapg.properties.feedbackDeclineReason, str, schemas.Unset] = schemas.unset,
                feedbackResponder: typing.Union['FeedbackResponder2f703c317dc910001c16504848720001', schemas.Unset] = schemas.unset,
                descriptor: typing.Union[MetaOapg.properties.descriptor, str, schemas.Unset] = schemas.unset,
                id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_0':
                return super().__new__(
                    cls,
                    *args,
                    response=response,
                    feedbackDeclined=feedbackDeclined,
                    feedbackDeclineReason=feedbackDeclineReason,
                    feedbackResponder=feedbackResponder,
                    descriptor=descriptor,
                    id=id,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                cls.all_of_0,
            ]


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FeedbackResponse2f703c317dc910001bd2de83d1590000':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from workday_performance_enablement_python_sdk.model.feedback_responder2f703c317dc910001c16504848720001 import FeedbackResponder2f703c317dc910001c16504848720001
